### ISSUE TITLE
Error 'NoMethodError: undefined method `valid_parameter_keys' for Excon::Middleware::NewRelicCrossAppTracing:Class' after upgrading 0.62.0 -> 0.63.0

### ISSUE THREAD

**Issue by henrik** [excon/excon#697]
Getting this error in an app on Ruby 2.5.5 and Rails 4.2.11.1 after upgrading excon from 0.62.0 to 0.63.0:

```
[GEM_ROOT]/gems/excon-0.63.0/lib/excon/connection.rb:401 :in `each`
 [GEM_ROOT]/gems/excon-0.63.0/lib/excon/connection.rb:401 :in `flat_map`
 [GEM_ROOT]/gems/excon-0.63.0/lib/excon/connection.rb:401 :in `valid_middleware_keys`
 [GEM_ROOT]/gems/excon-0.63.0/lib/excon/connection.rb:407 :in `validate_params`
 [GEM_ROOT]/gems/excon-0.63.0/lib/excon/connection.rb:71 :in `initialize`
 [GEM_ROOT]/gems/excon-0.63.0/lib/excon.rb:142 :in `new`
 [GEM_ROOT]/gems/excon-0.63.0/lib/excon.rb:142 :in `new`
 [GEM_ROOT]/gems/fog-core-2.1.2/lib/fog/core/connection.rb:57 :in `initialize`
 [GEM_ROOT]/gems/fog-aws-3.4.0/lib/fog/aws/storage.rb:560 :in `new`
 [GEM_ROOT]/gems/fog-aws-3.4.0/lib/fog/aws/storage.rb:560 :in `connection`
 [GEM_ROOT]/gems/fog-aws-3.4.0/lib/fog/aws/storage.rb:621 :in `_request`
 [GEM_ROOT]/gems/fog-aws-3.4.0/lib/fog/aws/storage.rb:616 :in `request`
 [GEM_ROOT]/gems/fog-aws-3.4.0/lib/fog/aws/requests/storage/head_object.rb:41 :in `head_object`
 [GEM_ROOT]/gems/fog-aws-3.4.0/lib/fog/aws/models/storage/files.rb:101 :in `head`
 [GEM_ROOT]/gems/carrierwave-0.11.2/lib/carrierwave/storage/fog.rb:381 :in `file`
 [GEM_ROOT]/gems/carrierwave-0.11.2/lib/carrierwave/storage/fog.rb:226 :in `read`
 [GEM_ROOT]/gems/carrierwave-0.11.2/lib/carrierwave/uploader/proxy.rb:46 :in `read`
[GEM_ROOT]/bundler/gems/prawn-4dc6592cff69/lib/prawn/images.rb:80 :in `build_image_object`
[GEM_ROOT]/bundler/gems/prawn-4dc6592cff69/lib/prawn/images.rb:69 :in `image`
 [PROJECT_ROOT]/app/documents/helpers/invoice_document_helper.rb:31 :in `invoice_header`
```

**Comment by jsantos** [comment]
I've also bumped into this, but I believe it's more related to Fog/New Relic than to excon itself...

**Comment by henrik** [comment]
Hehe, just tracked it to the same place.

That repo doesn't have an issue tracker, but I'll send off an email to New Relic, pointing them here..

I guess it's up to the excon devs if they want to treat this as a backwards incompatibility in excon or as New Relic using it wrong.

**Comment by ejoubaud** [comment]
The error was introduced by a change in excon, this LOC in particular: https://github.com/excon/excon/compare/v0.62.0...master#diff-93618fc68cdc1fde818cf4abd7102a14R401

FWIW I reckon this is a breaking interface contract change in excon's middlware. Feels like it warrants either a major version bump, or a check for the existence of the new `#valid_parameter_keys` on middlwares to preserve backward-compatibility.

**Comment by geemus** [comment]
Yeah, I think we should handle it missing more gracefully. We just happened to overlook this case when we were adding/updating things. (that said, it would be great if new relic would fix it on their end also).

**Comment by SirRawlins** [comment]
Running into this today too. Fingers crossed NR jump on it.

**Comment by geemus** [comment]
Yeah, sorry for the trouble. Reviewing the original change, the author included handling for this and I opted to skip it in the hopes of keeping things simpler (I had thought that middlewares which inherited from the base class would get a super method to solve the issue). Clearly I was wrong there, unfortunately, though it seemed a reasonable choice at the time. I'll try to get a patch out shortly to unbreak this on the excon side (though it would probably be good for new relic to fix as well, as I said.

**Comment by geemus** [comment]
Fix just released in v0.64.0.

**Comment by SirRawlins** [comment]
Awesome. 💪

**Comment by henrik** [comment]
New Relic support says:

> Thanks for bringing this to our attention. It looks like the developers at Excon have released a patch for this issue.
> 
> I escalated this issue to our Ruby agent team for review for any future changes.
> 
> At this time, it appear you can upgrade excon to 0.64 as a work-around.

**Comment by geemus** [comment]
FWIW, if their middleware had been a child of the Excon middleware base class it would have "just worked", but otherwise they could implement this method. (just in case they end up referring back to this).
