### ISSUE TITLE
Since 1.0.0, an empty `Content-Encoding` header causes a crash

### ISSUE THREAD

**Issue by Earlopain** [excon/excon#862]
Caused by https://github.com/excon/excon/commit/74c38a3f5c6329e624233f8b0a6e64d20c31bf89 + https://github.com/excon/excon/pull/858

Repro:

```
require "excon"
require "webmock"

include WebMock::API
WebMock.enable!

stub_request(:get, "https://example.com").to_return(body: "Hello World", headers: { "Content-Encoding" => "" })

Excon.get("https://example.com")
```

```
/home/user/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/excon-1.0.0/lib/excon/middlewares/decompress.rb:22:in 'Excon::Middleware::Decompress#response_call': undefined method 'casecmp' for nil (NoMethodError) (Excon::Error::Socket)
        from /home/user/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/excon-1.0.0/lib/excon/middlewares/response_parser.rb:12:in 'Excon::Middleware::ResponseParser#response_call'
        from /home/user/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/excon-1.0.0/lib/excon/connection.rb:472:in 'Excon::Connection#response'
        from /home/user/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/excon-1.0.0/lib/excon/connection.rb:297:in 'Excon::Connection#request'
        from /home/user/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/excon-1.0.0/lib/excon.rb:256:in 'Excon.get'
        from test.rb:9:in '<main>'
/home/user/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/excon-1.0.0/lib/excon/middlewares/decompress.rb:22:in 'Excon::Middleware::Decompress#response_call': undefined method 'casecmp' for nil (NoMethodError)
```

The fix seems easy enough and I'd do it myself but I'm not familiar with the test framework.

**Comment by geemus** [comment]
Thanks for the detailed report, I think the changes I just made should fix that.

**Comment by Earlopain** [comment]
Yes, I believe that is good. Thanks!
